# Generated by Django 4.2.1 on 2023-05-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asosiy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='holat',
            field=models.CharField(choices=[('bajaridi', 'bajarildi'), ('bajarilmadi', 'bajarilmadi'), ('boshlanmadi', 'boshlanmadi')], max_length=100),
        ),
    ]
