# Generated by Django 4.2.1 on 2023-05-27 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Asosiy', '0002_alter_plan_holat'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='foydalanuvchi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='plan',
            name='holat',
            field=models.CharField(choices=[('bajaridi', 'bajarildi'), ('bajarilmadi', 'bajarilmadi'), ('yangi', 'yangi')], max_length=100),
        ),
    ]
