# Generated by Django 4.2.1 on 2023-05-29 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Asosiy', '0004_alter_plan_batafsil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='holat',
            field=models.CharField(choices=[('bajarilmoqda', 'bajarilmoqda'), ('bajarilmadi', 'bajarilmadi'), ('boshlanmadi', 'boshlanmadi')], max_length=100),
        ),
        migrations.CreateModel(
            name='Muallif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('kitob_soni', models.PositiveIntegerField()),
                ('jins', models.CharField(choices=[('Erkak', 'Erkak'), ('Ayol', 'Ayol')], max_length=30)),
                ('Tirik', models.BooleanField()),
                ('tugulgan_yil', models.DateField()),
                ('foydalanuvchi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
